# Activation de l'environnement virtuel
Ac_venv:
    source mon_env/bin/activate

# Désactivation de l'environnement virtuel
Des_venv:
    deactivate

# Installation des dépendances
install:
    pip install -r requirements.txt

# Lancer le WAF en développement
run:
    python3 app.py

# Lancer le WAF en production
run_prod:
    gunicorn -w 4 -b 0.0.0.0:5000 app:app

# Exécuter les tests
test:
    pytest tests/

# Entraîner le modèle IA
train_model:
    python3 train_model.py